spring:
  cloud:
    gateway:
        routes:
          - id: r1
            uri: "http://localhost:8088"
            predicates:
              - Path=/clients/**

          - id: r2
            uri: "http://localhost:8088"
            predicates:
              - Path=/client/1/**
              -
          - id: r3
            uri: "http://localhost:8089"
            predicates:
              - Path=/voitures/**
